name: Test Secrets

on:
  workflow_dispatch: # Solo ejecución manual

jobs:
  test-secrets:
    runs-on: ubuntu-latest

    steps:
    - name: Test Supabase Secrets
      run: |
        echo "🔍 Verificando configuración de secrets..."

        if [ -z "$SUPABASE_ANON_KEY" ]; then
          echo "❌ SUPABASE_ANON_KEY no está configurado"
          exit 1
        else
          echo "✅ SUPABASE_ANON_KEY está configurado (longitud: ${#SUPABASE_ANON_KEY})"
        fi

        if [ -z "$SUPABASE_EDGE_FUNCTION_URL" ]; then
          echo "❌ SUPABASE_EDGE_FUNCTION_URL no está configurado"
          exit 1
        else
          echo "✅ SUPABASE_EDGE_FUNCTION_URL: $SUPABASE_EDGE_FUNCTION_URL"
        fi

        echo "🎉 Todos los secrets están configurados correctamente!"
      env:
        SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
        SUPABASE_EDGE_FUNCTION_URL: ${{ secrets.SUPABASE_EDGE_FUNCTION_URL }}